export const cardData = [
  {
    name: "room-card1",
    roomType: "Standard Room",
    roomPrice: "$500",
    bedType: "King Size",
    roomSize: "55sq ft",
    capacity: "2 Adults, 0 Child",
    roomView: "Garden",
    imgSrc: "http://127.0.0.1:5050/images_room-category_room-category-img-1",
  },
  {
    name: "room-card2",
    roomType: "Deluxe Room",
    roomPrice: "$1000",
    bedType: "King Size",
    roomSize: "75sq ft",
    capacity: "2 Adults, 1 Child",
    roomView: "Farm View",
    imgSrc: "http://127.0.0.1:5050/images_room-category_room-category-img-2",
  },
  {
    name: "room-card3",
    roomType: "Super Deluxe Room",
    roomPrice: "$2500",
    bedType: "King Size",
    roomSize: "85sq ft",
    capacity: "2 Adults, 2 Child",
    roomView: "Library",
    imgSrc: "http://127.0.0.1:5050/images_room-category_room-category-img-13",
  },
  {
    name: "card4",
    roomType: "Luxurios Room",
    roomPrice: "$5000",
    bedType: "King Size",
    roomSize: "155sq ft",
    capacity: "2 Adults, 0 Child",
    roomView: "Sea View",
    imgSrc: "http://127.0.0.1:5050/images_room-category_room-category-img-4",
  },
];
